<script src="<?php echo base_url() ?>assets/backend/js/jquery-1.10.2.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/inspinia.js" type="text/javascript"></script>
<!--<script src="<?php echo base_url() ?>assets/backend/js/jquery-ui-1.10.4.min.js" type="text/javascript"></script>-->

<script src="<?php echo base_url() ?>assets/backend/js/plugins/chosen/chosen.jquery.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/datapicker/bootstrap-datepicker.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/datapicker/bootstrap-datepicker.es.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/dataTables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/dataTables/dataTables.bootstrap.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/dropzone/dropzone.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/easypiechart/jquery.easypiechart.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/fancybox/jquery.fancybox.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/ionRangeSlider/ion.rangeSlider.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/jasny/jasny-bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/jeditable/jquery.jeditable.js" type="text/javascript"></script>
<!--<script src="<?php echo base_url() ?>assets/backend/js/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>-->
<script src="<?php echo base_url() ?>assets/backend/js/plugins/jsKnob/jquery.knob.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/metisMenu/jquery.metisMenu.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/nouslider/jquery.nouislider.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/pace/pace.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/peity/jquery.peity.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/staps/jquery.steps.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/switchery/switchery.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/jquery-validate/jquery.validate.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/jquery-validate/additional-methods.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/colorpicker/tinycolor.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/colorpicker/bootstrap.colorpickersliders.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/fancybox/jquery.fancybox.js?v=2.1.5" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/tagsinput/bootstrap-tagsinput.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/passrev/passrev.js" type="text/javascript"></script>

<script src="<?php echo base_url() ?>assets/backend/plugins/typeahead/typeahead.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/alertas/bootbox.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/cropper/jquery.imgareaselect.pack.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/ajaxuploadfile/jquery.ajaxfileupload.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/summernote/summernote.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/morris/morris.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/morris/raphael-min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/livevalidation/livevalidation_standalone.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/oocharts/oocharts.min.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/plugins/sudaca/sudaca.js" type="text/javascript"></script>
<script src="<?php echo base_url() ?>assets/backend/js/plugins/input_mask/jquery.maskedinput.min.js" type="text/javascript"></script>

